# Generated by Django 4.2.7 on 2023-11-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='bizimle elaqe')),
                ('description', models.TextField(verbose_name='bizim haqqimizda')),
                ('mail', models.CharField(max_length=255, verbose_name='mail')),
                ('tel', models.CharField(max_length=255, verbose_name='telefon nomresi')),
                ('subject', models.CharField(max_length=255, verbose_name='movzu')),
                ('mesage', models.CharField(max_length=255, verbose_name='mesage')),
            ],
            options={
                'verbose_name': 'bizim haqqimizda',
                'verbose_name_plural': 'bizim haqqimizdakilar',
                'ordering': ('name',),
            },
        ),
    ]
