# Generated by Django 4.2.7 on 2023-11-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=255, verbose_name='card adi')),
                ('description', models.TextField(verbose_name='bizim haqqimizda')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
            options={
                'verbose_name': 'bizim haqqimizda',
                'verbose_name_plural': 'bizim haqqimizdakilar',
                'ordering': ('card_title',),
            },
        ),
    ]
