# Generated by Django 4.2.7 on 2023-11-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='description',
        ),
    ]
