# Generated by Django 4.2.7 on 2023-11-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_remove_contact_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='tel',
        ),
    ]
